export { createAuditLog, listAuditLogs, sanitizeAuditJson } from "./audit.js";
export {
  buildAccountAccessStatus,
  checkForecastAccess,
  fullForecastAccessEntitlementType,
  fullForecastAccessProductCodes,
  getForecastAccessSettings,
  isFullForecastAccessProduct,
  isInternalTrialProduct,
  isPublicPurchasableBillingProduct,
  monthlyFullAccessProductCode,
  quarterlyFullAccessProductCode,
  resolveUserForecastAccess,
  trialFullAccessProductCode,
  upgradeRequiredMessage,
  upgradeRequiredResponse,
  yearlyFullAccessProductCode,
} from "./access.js";
export type {
  AccountAccessStatus,
  ForecastAccessDecision,
  ForecastAccessReason,
  ForecastAccessSettings,
  ForecastAccessStatus,
  ForecastAccessTier,
} from "./access.js";
export {
  AdminUserNotFoundError,
  InvalidAdminRoleAssignmentError,
  LastAdminAccessChangeError,
  adminUserAuditSnapshot,
  createAdminManagedUser,
  disableUserAccount,
  enableUserAccount,
  generateAdminTemporaryPassword,
  getAdminUserDetail,
  getUserOperationalSummary,
  listAdminUsers,
  listUserAuditLogsForAdmin,
  listUserCreditLedgerForAdmin,
  listUserEntitlementsForAdmin,
  listUserForecastHistoryForAdmin,
  listUserPaymentOrdersForAdmin,
  listUserSessionsForAdmin,
  principalCanManageAdminRoles,
  resetUserPasswordByAdmin,
  revokeUserSessionsByAdmin,
  updateAdminManagedUser,
  updateUserRolesByAdmin,
} from "./admin-users.js";
export {
  AdminPaymentOrderNotFoundError,
  adminOrderAuditSnapshot,
  getAdminPaymentOrderDetail,
  getOrderOperationalTimeline,
  listAdminPaymentOrders,
  listOrderCreditLedger,
  listOrderEntitlements,
  listPaymentNotificationsForAdmin,
  updateAdminPaymentOrderDetail,
} from "./admin-orders.js";
export {
  assertPermission,
  calculateSessionExpiresAt,
  capRotatedSessionExpiresAt,
  createRefreshToken,
  createPublicUserAccount,
  DuplicateUserEmailError,
  DuplicateUserPhoneError,
  LastAdminAccountDeletionError,
  createUserSession,
  getActiveUserSessionByRefreshToken,
  getUserAccountByIdentifier,
  getUserAuthContextByEmail,
  getUserAuthContextByIdentifier,
  getUserAuthContextById,
  getUserAuthContextWithPasswordById,
  hashRefreshToken,
  hasPermission,
  adminRoleCodes,
  isLastActiveAdminUser,
  isAdminRoleLike,
  isSessionExpired,
  principalHasAdminAccess,
  principalHasAdminRole,
  requiredAdminPermissions,
  resolveRoleBasedSessionTtlDays,
  resolveRoleBasedSessionType,
  revokeUserSessions,
  revokeUserSessionByRefreshToken,
  softDeleteUserAccount,
  MissingUserIdentifierError,
  normalizeUserEmail,
  normalizeUserPhone,
  safeUser,
  touchUserLastLogin,
  updateUserEmail,
  updateUserPassword,
  updateUserPhone,
} from "./auth.js";
export {
  consumeAuthVerificationCode,
  createAuthVerificationCode,
  findLatestActiveAuthVerificationCode,
  hashAuthVerificationCode,
  incrementAuthVerificationAttempt,
  pruneExpiredAuthVerificationCodes,
  resolveVerificationCodeSecret,
  verifyAuthVerificationCode,
} from "./auth-verification.js";
export { disconnectPrismaClient, getPrismaClient } from "./client.js";
export {
  clearUserForecastHistory,
  deleteUserForecastHistory,
  listUserForecastHistory,
  saveUserForecastHistory,
} from "./forecast-history.js";
export {
  assertProviderType,
  assertSettingValueType,
  isLocationSource,
  isLocationType,
  isProviderType,
  isSettingValueType,
  isViewDirection,
  locationSources,
  locationTypes,
  providerTypes,
  settingValueTypes,
  userStatuses,
  viewDirections,
} from "./constants.js";
export {
  AdminVerificationError,
  createOrUpdateAdmin,
  createOrUpdateSuperAdmin,
  formatCreateAdminResult,
  formatVerifyAdminResult,
  readCreateAdminEnv,
  readVerifyAdminEnv,
  runCreateAdminFromEnv,
  runVerifyAdminFromEnv,
  verifyAdminBootstrap,
  verifySuperAdmin,
} from "./create-admin.js";
export {
  createLocation,
  createPhotoSpot,
  deleteLocation,
  deletePhotoSpot,
  getLocation,
  getPhotoSpot,
  listLocations,
  listPhotoSpots,
  updateLocation,
  updatePhotoSpot,
} from "./locations.js";
export {
  getProviderConfig,
  getRuntimeProviderConfig,
  listProviderConfigs,
  updateProviderConfig,
  validateProviderCode,
} from "./providers.js";
export {
  assertUserOwnsPaymentOrder,
  consumeUserCredit,
  createPaymentOrder,
  getBillingProductByCode,
  getPaymentOrderByOrderNo,
  grantFullForecastAccessFromOrderOnce,
  grantPaymentEntitlementOnce,
  grantRegistrationTrialForUserOnce,
  InvalidPaymentStatusTransitionError,
  listBillingProducts,
  listUserEntitlements,
  listUserPaymentOrders,
  markPaymentOrderPaid,
  PaymentAmountMismatchError,
  PaymentEntitlementGrantError,
  PaymentOrderAccessDeniedError,
  PaymentOrderNotFoundError,
  recordPaymentNotification,
  updatePaymentNotificationStatus,
  updatePaymentOrderStatus,
} from "./payments.js";
export { buildSeedData } from "./seed-data.js";
export { seedDatabase } from "./seed.js";
export { maskSecretJson, maskSecretString, maskSecretValue } from "./secrets.js";
export {
  hashPassword,
  hashUserPassword,
  minimumAdminPasswordLength,
  minimumUserPasswordLength,
  validateAdminPassword,
  validateUserPassword,
  verifyPassword,
} from "./passwords.js";
export { safeProviderConfig, safeSystemSetting } from "./serializers.js";
export {
  getSystemSetting,
  listSystemSettings,
  setSystemSetting,
  validateSettingKey,
  validateSettingValue,
} from "./settings.js";
export { createApiUsageLog } from "./usage.js";
export type {
  AdminAuditLogInput,
  AdminAuditLogRecord,
  ApiUsageLogInput,
  AuthVerificationChannel,
  AuthVerificationCodeRecord,
  AuthVerificationPurpose,
  AuthenticatedPrincipal,
  BillingProductRecord,
  CalibrationLevel,
  CalibrationStatsRecord,
  DatabaseClient,
  EntitlementType,
  ForecastReplayResultRecord,
  ForecastReplayRunRecord,
  ForecastReplayStatus,
  ForecastReplayTarget,
  HistoricalWeatherSampleRecord,
  HistoricalWeatherSourceProvider,
  ObservedOutcomeRecord,
  ObservedOutcomeSource,
  ObservedResult,
  PaymentNotificationRecord,
  PaymentNotifyStatus,
  PaymentOrderRecord,
  PaymentOrderStatus,
  PaymentProviderCode,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  LocationRecord,
  LocationSource,
  LocationType,
  PhotoSpotRecord,
  ProviderConfigRecord,
  ProviderType,
  RainImpactLevel,
  SafeRole,
  SafeProviderConfig,
  SafeSystemSetting,
  SafeUser,
  SafeUserProfile,
  SettingValueType,
  SystemSettingRecord,
  TerrainElevationCacheRecord,
  TransparencyLevel,
  UserRecord,
  UserForecastHistoryRecord,
  UserProfileRecord,
  UserSessionRecord,
  UserStatus,
  ViewDirection,
  WhiteoutLevel,
} from "./types.js";
export type { RoleBasedSessionTtlConfig, RoleBasedSessionType } from "./auth.js";
export type {
  AdminOrderAuditLogItem,
  AdminOrderCreditLedgerItem,
  AdminOrderEntitlementItem,
  AdminOrderTimelineItem,
  AdminPaymentNotificationItem,
  AdminPaymentOrderDetail,
  AdminPaymentOrderListItem,
  AdminPaymentOrderListResult,
  AdminPaymentOrderListSort,
  ListAdminPaymentOrdersInput,
} from "./admin-orders.js";
export type {
  AdminUserAuditLogItem,
  AdminUserCreditLedgerItem,
  AdminUserDetail,
  AdminUserEntitlementItem,
  AdminUserForecastHistoryItem,
  AdminUserListItem,
  AdminUserListResult,
  AdminUserOrderItem,
  AdminUserSessionItem,
  AdminUserListSort,
  ListAdminUsersInput,
} from "./admin-users.js";

export type DatabasePackageStatus = {
  readonly prismaSchema: "database_foundation";
  readonly businessModels: "created";
};

export const databasePackageStatus: DatabasePackageStatus = {
  prismaSchema: "database_foundation",
  businessModels: "created",
};
